name: Test
on: push
jobs:
  ubuntu22-clang23-x86_64:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_LINUX: ${{ secrets.SDE_LINUX }}
        TMP_DIR: ${{ runner.temp }}
      run: |
        set -e
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends ninja-build
        ci/llvm-linux.sh
        curl -o "$TMP_DIR/sde.tar.xz" -L "$SDE_LINUX"
        mkdir "$TMP_DIR/sde-bin"
        tar -C "$TMP_DIR/sde-bin" -xJf "$TMP_DIR/sde.tar.xz" --strip 1
        sudo ln -s $TMP_DIR/sde-bin/sde64 /usr/bin/sde
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci/run.sh build-release -DCMAKE_PREFIX_PATH=$VCPKG_INSTALLATION_ROOT/installed/x64-linux -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DKFR_ARCH_TESTS=sse2,sse3,sse41,avx,avx2,avx512 -DKFR_ARCH=avx2 -DKFR_USE_SDE=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release

  ubuntu22-clang23-arm:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends ninja-build g++-arm-linux-gnueabihf qemu-system-arm qemu-user
        ci/llvm-linux.sh
        ci/run.sh build-release -DENABLE_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/arm.cmake

  ubuntu22-clang23-arm64:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends ninja-build g++-aarch64-linux-gnu qemu-system-arm qemu-user
        ci/llvm-linux.sh
        ci/run.sh build-release -DENABLE_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/aarch64.cmake

  ubuntu24-clang23-riscv64:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends llvm ninja-build qemu-system-riscv64 qemu-user gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
        ci/llvm-linux.sh
        ci/run.sh build-release -DKFR_ENABLE_DFT=OFF -DENABLE_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/riscv64.cmake

  ubuntu24-gcc14-x86_64:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_LINUX: ${{ secrets.SDE_LINUX }}
        TMP_DIR: ${{ runner.temp }}
      run: |
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends ninja-build g++-14
        curl -o "$TMP_DIR/sde.tar.xz" -L "$SDE_LINUX"
        mkdir "$TMP_DIR/sde-bin"
        tar -C "$TMP_DIR/sde-bin" -xJf "$TMP_DIR/sde.tar.xz" --strip 1
        sudo ln -s $TMP_DIR/sde-bin/sde64 /usr/bin/sde
        ci/run.sh build-release -DKFR_ARCH=target -DCMAKE_CXX_COMPILER=g++-14 -DKFR_ARCH_TESTS=sse2,sse3,avx,avx2,avx512 -DCMAKE_BUILD_TYPE=Release -DKFR_USE_SDE=ON

  ubuntu24-clang19-arm:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends build-essential cmake ninja-build clang-19
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci/run.sh build-release -DCMAKE_PREFIX_PATH=/usr/local/share/vcpkg/installed/arm64-linux -DKFR_ARCH=target -DENABLE_EXAMPLES=OFF -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_BUILD_TYPE=Release

  ubuntu24-gcc-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        sudo apt-get update -qq
        sudo apt-get install -y -q --no-install-recommends software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update -qq && sudo apt-get install -y -q --no-install-recommends build-essential cmake ninja-build gcc-16 g++-16
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci/run.sh build-release -DCMAKE_PREFIX_PATH=/usr/local/share/vcpkg/installed/arm64-linux -DKFR_ARCH=target -DENABLE_EXAMPLES=OFF -DCMAKE_C_COMPILER=gcc-16 -DCMAKE_CXX_COMPILER=g++-16 -DCMAKE_BUILD_TYPE=Release

  windows2025-clang23-x86:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_WINDOWS2: ${{ secrets.SDE_WINDOWS2 }}
        TMP_DIR: ${{ runner.temp }}
        VCPKG_DEFAULT_TRIPLET: x86-windows-static-md
        VCPKG_HOST_TRIPLET: x86-windows-static-md
      shell: cmd
      run: |
        curl -L --fail --retry 3 -o "%TEMP%\LLVM-23.1.0-win64.msi" https://github.com/llvm/llvm-project/releases/download/llvmorg-23.1.0/LLVM-23.1.0-win64.msi
        msiexec /i "%TEMP%\LLVM-23.1.0-win64.msi" /quiet /norestart
        choco install ninja --no-progress -y
        curl -o "%TMP_DIR%\sde.tar.xz" -L %SDE_WINDOWS2%
        mkdir C:\sde
        tar -C C:\sde -xf "%TMP_DIR%\sde.tar.xz" --strip-components=1
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        set CXXFLAGS=-m32
        set CFLAGS=-m32
        set PATH=C:\sde;%PATH%
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci\run.cmd build-release -DCMAKE_PREFIX_PATH=%VCPKG_INSTALLATION_ROOT%/installed/x86-windows-static-md -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DKFR_ARCH_TESTS=sse2,ssse3,sse42,avx,avx2 -DKFR_ENABLE_MULTIARCH=ON -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe" -DKFR_USE_SDE=ON -DKFR_ARCH=sse2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_AR="C:/Program Files/LLVM/bin/llvm-lib.exe"

  windows2025-clang23-x86_64:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_WINDOWS2: ${{ secrets.SDE_WINDOWS2 }}
        TMP_DIR: ${{ runner.temp }}
        VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
        VCPKG_HOST_TRIPLET: x64-windows-static-md
      shell: cmd
      run: |
        curl -L --fail --retry 3 -o "%TEMP%\LLVM-23.1.0-win64.msi" https://github.com/llvm/llvm-project/releases/download/llvmorg-23.1.0/LLVM-23.1.0-win64.msi
        msiexec /i "%TEMP%\LLVM-23.1.0-win64.msi" /quiet /norestart
        choco install ninja --no-progress -y
        curl -o "%TMP_DIR%\sde.tar.xz" -L %SDE_WINDOWS2%
        mkdir C:\sde
        tar -C C:\sde -xf "%TMP_DIR%\sde.tar.xz" --strip-components=1
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=C:\sde;%PATH%
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci\run.cmd build-release -DCMAKE_PREFIX_PATH=%VCPKG_INSTALLATION_ROOT%/installed/x64-windows-static-md -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DKFR_ARCH_TESTS=sse2,ssse3,sse42,avx,avx2,avx512 -DKFR_ENABLE_MULTIARCH=ON -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe" -DKFR_USE_SDE=ON -DKFR_ARCH=sse2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_AR="C:/Program Files/LLVM/bin/llvm-lib.exe"


  windows11-clang-arm64:
    runs-on: windows-11-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        VCPKG_DEFAULT_TRIPLET: arm64-windows-static-md
        VCPKG_HOST_TRIPLET: arm64-windows-static-md
      shell: cmd
      run: |
        curl -L --fail --retry 3 -o "%TEMP%\LLVM-23.1.0-woa64.msi" https://github.com/llvm/llvm-project/releases/download/llvmorg-23.1.0/LLVM-23.1.0-woa64.msi
        msiexec /i "%TEMP%\LLVM-23.1.0-woa64.msi" /quiet /norestart
        choco install ninja --no-progress -y
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" arm64
        ci\run.cmd build-release -DCMAKE_PREFIX_PATH=%VCPKG_INSTALLATION_ROOT%/installed/arm64-windows-static-md -DCMAKE_C_COMPILER_TARGET=arm64-pc-windows-msvc -DCMAKE_CXX_COMPILER_TARGET=arm64-pc-windows-msvc -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe" -DKFR_ARCH=neon -DCMAKE_BUILD_TYPE=Release -DCMAKE_AR="C:/Program Files/LLVM/bin/llvm-lib.exe"

  windows2025-msvc2026-x86:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_WINDOWS2: ${{ secrets.SDE_WINDOWS2 }}
        TMP_DIR: ${{ runner.temp }}
      shell: cmd
      run: |
        choco install ninja --no-progress -y
        curl -o "%TMP_DIR%\sde.tar.xz" -L %SDE_WINDOWS2%
        mkdir C:\sde
        tar -C C:\sde -xf "%TMP_DIR%\sde.tar.xz" --strip-components=1
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat"
        set PATH=C:\sde;%PATH%
        ci\run.cmd build-release -DKFR_ARCH_TESTS=sse2,ssse3,sse42,avx,avx2 -DKFR_ENABLE_MULTIARCH=ON -DKFR_USE_SDE=ON -DKFR_ARCH=sse2 -DCMAKE_BUILD_TYPE=Release

  windows2025-msvc2026-x86_64:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      env:
        SDE_WINDOWS2: ${{ secrets.SDE_WINDOWS2 }}
        TMP_DIR: ${{ runner.temp }}
      shell: cmd
      run: |
        choco install ninja --no-progress -y
        curl -o "%TMP_DIR%\sde.tar.xz" -L %SDE_WINDOWS2%
        mkdir C:\sde
        tar -C C:\sde -xf "%TMP_DIR%\sde.tar.xz" --strip-components=1
        call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=C:\sde;%PATH%
        ci\run.cmd build-release -DKFR_ARCH_TESTS=sse2,ssse3,sse42,avx,avx2 -DKFR_ENABLE_MULTIARCH=ON -DKFR_USE_SDE=ON -DKFR_ARCH=sse2 -DCMAKE_BUILD_TYPE=Release

  windows2022-msvc2022-x86_64:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      shell: cmd
      run: |
        choco install ninja --no-progress -y
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ci\run.cmd build-release -DCMAKE_BUILD_TYPE=Release


  macos15-xcode16-x86_64:
    runs-on: macos-15-intel
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci/run.sh build-release -DCMAKE_PREFIX_PATH=$VCPKG_INSTALLATION_ROOT/installed/x64-osx -DCMAKE_OSX_ARCHITECTURES=x86_64 -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DKFR_ARCH_TESTS=sse42,avx -DKFR_ARCH=target -DCMAKE_BUILD_TYPE=Release      

  macos26-xcode26-arm64:
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Tests
      run: |
        set -e
        vcpkg install --overlay-ports=cmake/ports libflac minimp3 alac
        ci/run.sh build-release -DCMAKE_PREFIX_PATH=$VCPKG_INSTALLATION_ROOT/installed/arm64-osx -DCMAKE_OSX_ARCHITECTURES=arm64 -DKFR_ENABLE_CAPI_BUILD=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DKFR_ARCH=target -DCMAKE_BUILD_TYPE=Release

